name: prometheus-pushgateway # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Prometheus Push Gateway # 79 char long summary
description: |
  Prometheus Push Gateway

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots
parts:
  go-build:
    # See 'snapcraft plugins'
    plugin: go
    source: ./
    build-snaps:
     - go
    organize:
      pushgateway: bin/
apps:
  pushgateway:
    daemon: simple
    command: bin/pushgateway